### ISSUE TITLE
Failure when the files are already downloaded

### ISSUE THREAD

**Issue by Uxorious** [rraptorr/oracle-java8#12]
I'm using the Ubuntu wrapper provided by https://github.com/marsjk/oab-java6 or https://github.com/ladios/oab-java6.

It used to work great, but I'm seeing a failure with JAVA8 right now.

As far as I can tell, the failure happens because the file has already been downloaded.
Since the "prepare.sh" script tries to resume the download, it will send a start address of the entire file length, and Oracle/Akamai now returns error 416 in that case.

Any idea how to handle this error?

**Comment by rraptorr** [comment]
That really is an issue with oab-java6 and should be reported there. However, I've removed -C flag from curl, since it does not work anyway.
