### ISSUE TITLE
Build scripts update for oracle-java-8.112 (Debian jessie)

### ISSUE THREAD

**Issue by jaikumarSharma** [rraptorr/oracle-java8#14]
Dear Rraptorr, since oracle has release a new verion of JRE/JDK , i cloned your script of 8.102 and i've made the following change locally in the scripts 

1. Updated the checksum of jdk (64bit) and 32 bit in rules file.
2.Update the changelog to 8.112-01
3.download/prepare the sources using 'prepare.sh'
4.prepeared .dsc to be used with pbuilder chroot build.

But build failed with the message:
debian/control did change, please restart the build
debian/rules:168: recipe for target 'debian/control' failed
make: *** [debian/control] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2

Would you please check what is wrong? or just let me know i can do it and also upload the changes to if you like to,
Thank you in advance!
Regards

**Comment by rraptorr** [comment]
Will look into this in a week or so as I'm currently away.

**Comment by roock** [comment]
fyi: I could successfully build with jessie/amd64 (we are only building amd64).
My changes are here:
https://github.com/roock/oracle-java8/commit/e8c7edd34e9b6e9d72e68cf7bc7cf8aa4733365d
