### ISSUE TITLE
jvisualvm tool ?

### ISSUE THREAD

**Issue by hhromic** [rraptorr/oracle-java8#16]
Hi !
First of all, great packaging!
However I noticed that the `jvisualvm` JDK tool is not enabled by default to be installed in `/usr/bin` using the alternatives system as the rest of the JDK tools.  This tool was recently (since `1.8.0_131`) released officially from Oracle now in the JDK.

I noticed the following rule (last line) explicitly filtering it out in `debian/rules`:

    all_jdk_tools   = $(notdir $(wildcard $(srcdir)/bin/*))
    jdk_tools       = $(filter-out $(all_jre_tools), $(all_jdk_tools))
    jdk_tools_alt   = $(filter-out jvisualvm, $(jdk_tools))

Is there any reason for this? can `jvisualvm` be enabled ?

Thanks!
Hugo.

**Comment by rraptorr** [comment]
Alternatives are used to select a version of a command, from different packages/implementations, with the same name (for example awk -> gawk or mawk, java -> opendjk or oracle).
jvisualvm has no alternatives, it is not available in openjdk or any other java version, it is only present in Oracle JDK. Why would you want alternatives for that?

**Comment by hhromic** [comment]
Thanks for your answer.
Actually I'm not asking for an alternative in that sense, but for the binary to be available in the path like the other tools (java, javac, etc.). I mentioned the alternatives system (I know how that system works) to make it consistent to the way you are providing all the binaries of the package.
The other way to provide the binary in the path would be to install the binary under /usr/bin which is something I don't think is a good idea compared to just setting a single alternative for jvisualvm.
What do you think? The main purpose of my question is to bring jvisualvm into the search path with the rest of the tools.
