### ISSUE TITLE
Java 9

### ISSUE THREAD

**Issue by tomposmiko** [rraptorr/oracle-java8#17]
hi,

Are you going to create a similar project for Java 9?

**Comment by rraptorr** [comment]
No, definitely not. This project is based on very old Java packaging dating back to Java 5. It is basically quite a mess with various hacks. Given that Java 9 changes quite a lot of things, this project probably should be rewritten from scratch.
For quite some time there is 'java-package' tool available in Debian, that can package Java for you. It does not support Java 9 yet, but I've seen people working on it. Extending that tool is probably the way to go.
