### ISSUE TITLE
Java 8.152 - "Cannot represent change  to UnlimitedJCEPolicyJDK8/US_export_policy.jar: binary file contents changed"

### ISSUE THREAD

**Issue by resoli** [rraptorr/oracle-java8#18]
During `dpkg-buildpackage -uc -us>` phase I obtain:
>dpkg-source: Informazioni: using source format '3.0 (quilt)'
>dpkg-source: Informazioni: building oracle-java8 using existing ./oracle-java8_8.152.orig-i586.tar.gz ./oracle-java8_8.152.orig-x64.tar.gz ./oracle-java8_8.152.orig.tar.gz
>dpkg-source: Errore: cannot represent change to UnlimitedJCEPolicyJDK8/US_export_policy.jar: binary file contents changed
>dpkg-source: Errore: add UnlimitedJCEPolicyJDK8/US_export_policy.jar in debian/source/include-binaries if you want to store the modified binary in the debian tarball

**Comment by rraptorr** [comment]
Do a clean checkout and repeat. Or remove UnlimitedJCEPolicyJDK8 directory. Those files ar eno longer present in 8u152.

**Comment by resoli** [comment]
Thanks, building now ...
