### ISSUE TITLE
Error when building java8 162

### ISSUE THREAD

**Issue by nemessiss81** [rraptorr/oracle-java8#19]
Hello

I receive the following error when building:

`
    dpkg-buildpackage -uc -us
    dpkg-buildpackage: source package oracle-java8
    dpkg-buildpackage: source version 8.162-2
    dpkg-buildpackage: source distribution stable
    dpkg-buildpackage: source changed by Janusz Dziemidowicz <rraptorr@nails.eu.org>
    dpkg-buildpackage: host architecture amd64
     dpkg-source --before-build oracle-java8
     debian/rules clean
    dh_testdir
    dh_testroot
    rm -f *-stamp
    rm -rf tmp-*
    rm -f debian/*.debhelper debian/control.old
    rm -f debian/oracle-java8-bin.substvars.tmp
    for f in debian/*.in; do \
    	  f2=$(echo $f | sed 's/JB/oracle-java8/;s/\.in$//'); \
	  case "$f2" in debian/control) continue; esac; \
	  rm -f $f2; \
	done
    rm -f debian/oracle-java8*.links
    rm -f debian/*.debhelper.log
    dh_clean
     dpkg-source -b oracle-java8
    dpkg-source: info: using source format `3.0 (quilt)'
    dpkg-source: info: building oracle-java8 using existing ./oracle-java8_8.162.orig-i586.tar.gz     ./oracle-java8_8.162.orig-x64.tar.gz ./oracle-java8_8.162.orig.tar.gz
dpkg-source: error: cannot represent change to UnlimitedJCEPolicyJDK8/US_export_policy.jar: binary file contents changed
dpkg-source: error: add UnlimitedJCEPolicyJDK8/US_export_policy.jar in debian/source/include-binaries if you want to store the modified binary in the debian tarball
dpkg-source: error: cannot represent change to UnlimitedJCEPolicyJDK8/local_policy.jar: binary file contents changed
dpkg-source: error: add UnlimitedJCEPolicyJDK8/local_policy.jar in debian/source/include-binaries if you want to store the modified binary in the debian tarball
dpkg-source: error: unrepresentable changes to source
dpkg-buildpackage: error: dpkg-source -b oracle-java8 gave error exit status 2
`

Please advice.
Thank you!

**Comment by romanshypovskyi** [comment]
try:
git clean -f -x -d
sh ./prepare.sh
dpkg-buildpackage -uc -us

**Comment by nemessiss81** [comment]
Thank you for your fast reply.
git clean -f -x -d did the trick

Thank you!
