### ISSUE TITLE
8u202 has been released

### ISSUE THREAD

**Issue by hhromic** [rraptorr/oracle-java8#21]
https://www.oracle.com/technetwork/java/javase/8u-relnotes-2225394.html

btw, thanks a million for this repository, it has been really useful.

**Comment by rraptorr** [comment]
It is pretty annoying to see issues created a few hours after a new version of Java is released. I am well aware of that, the date was announced several months ago.

**Comment by hhromic** [comment]
I'm very sorry, I didn't mean to offend or pressure you at all. I honestly thought the version was released since a while. I made the issue to follow the format of the last issue just as a reminder. I sincerely apologise as I highly respect and value your work with this.

**Comment by rraptorr** [comment]
No problem ;) Java release schedule is public and announced a year in advance: https://www.oracle.com/technetwork/topics/security/alerts-086861.html

Please also note that is the very last public Java 8 update. You have to switch to Java 11 or pay Oracle for commercial Java 8 support.

**Comment by hhromic** [comment]
Thanks for the info and I see now. I myself don't work so actively with Java anymore, but I'm in charge of maintaining a bunch of internal legacy servers up-to-date with Java 8 (hence why I appreciate the convenience of your packaging). I already notified my users that this is the last of Java 8 :)

Kudos again.
