### ISSUE TITLE
Provide the virtual package "default-jre-headless"

### ISSUE THREAD

**Issue by jhermann** [rraptorr/oracle-java8#5]
On Wheezy and Squeeze "openjdk-6" is pulled in when packages like "groovy" are installed, because they depend on the virtual package "default-jre-headless". A "Provides" should be added to the control file, and the same should be done for the Java7 project.

Can do a PR if needed (should be a 1-line addition).

**Comment by rraptorr** [comment]
I will not accept this. default-jre (or default-jre-headless) is not a virtual package. It is an actual package that creates a 'default-java' JVM in the system. Also, default-jre has Conflicts field set to default-jre, which would cause quite a havoc in the system for anyone trying to install oracle-java8-jre with default-jre.

Packages that run on any Java should depend on java-runtime (or javaX-runtime) which I already have in Provides. I believe that goovy package has incorrect depends on "default-jre-headless | sun-java6-jre", it should be "default-jre-headless | java6-runtime", please report it to groovy package maintainer.
