### ISSUE TITLE
8.45 tag isn't working correctly

### ISSUE THREAD

**Issue by justinthegeek** [rraptorr/oracle-java8#6]
When I clone the repo, and pull the tag, it gives me the last updated version instead of the newest.

`> git clone --mirror https://github.com/rraptorr/oracle-java8
Cloning into bare repository 'oracle-java8.git'...
remote: Counting objects: 268, done.
remote: Total 268 (delta 0), reused 0 (delta 0), pack-reused 268
Receiving objects: 100% (268/268), 66.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (154/154), done.
Checking connectivity... done.`
`> cd oracle-java8.git/`
`> git describe --abbrev=0 --tags`
`v8.40-1`
`> git describe --tags`
`v8.40-1-1-gd7169a8`

**Comment by jhermann** [comment]
The tag is placed in a branch (b765be8) for whatever reason and thus not reachable from HEAD, that is why.

Check out the tag directly.
